group: ''
metric_names:
- train/loss
- train/acc
- val/loss
- val/acc
- cpu/percent
- ram/used
- ram/percent
- gpu:0/load
- gpu:0/memory_used
- gpu:0/temperature
project: iris-demo
run_id: hf4264-240723_0210-tefumu
run_init_timestamp: '2024-07-23T02:10:28.554321'
run_path: ../demos/local/iris-demo/runs/hf4264-240723_0210-tefumu
syllabic_id: tefumu
train_config:
  criterion: CrossEntropyLoss()
  dataset: iris
  model: "DNN(\n  (net): Sequential(\n    (0): Linear(in_features=4, out_features=10,\
    \ bias=True)\n    (1): ReLU()\n    (2): Linear(in_features=10, out_features=3,\
    \ bias=True)\n    (3): Softmax(dim=1)\n  )\n)"
  optimizer: "Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n\
    \    capturable: False\n    differentiable: False\n    eps: 1e-08\n    foreach:\
    \ None\n    fused: None\n    lr: 0.001\n    maximize: False\n    weight_decay:\
    \ 0\n)"
