name: Checks

on:
  pull_request:
    branches:
      - main
      - "*"
  push:
    branches:
      - main

jobs:
  lint:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Install linters
        run: make setup-format RUN_GLOBAL=1

      - name: Run Format Checks
        run: make check-format RUN_GLOBAL=1
  
  check-deps:
    name: Check dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -
      
      - name: Poetry Plugins
        run: |
          poetry self add poetry-plugin-export
          poetry self show plugins

      - name: Check poetry.lock and .github/dev-requirements.txt
        run: make dep-check

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        run: uv pip install -r .github/dev-requirements.txt --system --no-deps # we already should have all dependencies exported into .github/dev-requirements.txt
      
      - name: Install torch (special)
        run: uv pip install torch==2.3.1+cpu --system --extra-index-url https://download.pytorch.org/whl/cpu

      - name: Install trnbl (local)
        run: uv pip install . --system

  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    # needs: [lint, check-deps]
    strategy:
      matrix:
        versions:
          - python: '3.10'
            torch: '2.3.1'
          - python: '3.11'
            torch: '2.3.1'
          - python: '3.12'
            torch: '2.3.1'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.versions.python }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies
        # install torch first to avoid pytorch index messing things up
        run: |
          uv pip install -r .github/dev-requirements.txt --system --no-deps
          uv pip install torch==${{ matrix.versions.torch}}+cpu --system --extra-index-url https://download.pytorch.org/whl/cpu
      
      - name: Install trnbl
        run: uv pip install . --system
      
      - name: tests
        run: make test RUN_GLOBAL=1 WARN_STRICT=1

      - name: notebook tests
        run: make test_notebooks RUN_GLOBAL=1 WARN_STRICT=1

      # - name: check typing
      #   run: make typing RUN_GLOBAL=1